name: 'lakehouse'
version: '1.0.0'
config-version: 2

profile: 'lakehouse'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse:
    bronze:
      materialized: view
      schema: bronze
    silver:
      materialized: table
      schema: silver
    gold:
      materialized: table
      schema: gold
