lakehouse:
  outputs:
    docker:  
      type: trino
      method: none
      user: admin
      database: iceberg
      schema: bronze
      host: trino
      port: 8080
      http_scheme: http
      threads: 2
      
    local:  
      type: trino
      method: none
      user: admin
      database: iceberg
      schema: dbt_default
      host: localhost
      port: 8082
      http_scheme: http
      threads: 2

  target: docker 
