-- ============================================
-- AUTO-GENERATED SQL FROM PARQUET SCHEMA
-- Generated by: scripts/generate_sql_from_parquet.py
-- ============================================

-- Create schemas
CREATE SCHEMA IF NOT EXISTS hive.lol_bronze;
CREATE SCHEMA IF NOT EXISTS iceberg.bronze;


-- ========== LADDER ==========

-- OPTION 1: Hive External → Iceberg CTAS (auto schema)
-- Hive External Table: ladder
CREATE TABLE IF NOT EXISTS hive.lol_bronze.ladder (
    platform VARCHAR,
    tier VARCHAR,
    league_points BIGINT,
    wins BIGINT,
    losses BIGINT,
    puuid VARCHAR,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET',
    external_location = 's3a://lol-bronze/ladder/'
);

-- Iceberg CTAS: ladder (auto schema from Hive)
CREATE TABLE IF NOT EXISTS iceberg.bronze.ladder AS
SELECT * FROM hive.lol_bronze.ladder;


-- OPTION 2: Explicit Iceberg CREATE + INSERT
-- Iceberg Table: ladder
CREATE TABLE IF NOT EXISTS iceberg.bronze.ladder (
    platform VARCHAR,
    tier VARCHAR,
    league_points BIGINT,
    wins BIGINT,
    losses BIGINT,
    puuid VARCHAR,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET'
);

-- Copy data from Hive to Iceberg
INSERT INTO iceberg.bronze.ladder
SELECT * FROM hive.lol_bronze.ladder;


-- ========== MATCH_IDS ==========

-- OPTION 1: Hive External → Iceberg CTAS (auto schema)
-- Hive External Table: match_ids
CREATE TABLE IF NOT EXISTS hive.lol_bronze.match_ids (
    match_id VARCHAR,
    puuid VARCHAR,
    platform VARCHAR,
    region VARCHAR,
    queue_id BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET',
    external_location = 's3a://lol-bronze/match_ids/'
);

-- Iceberg CTAS: match_ids (auto schema from Hive)
CREATE TABLE IF NOT EXISTS iceberg.bronze.match_ids AS
SELECT * FROM hive.lol_bronze.match_ids;


-- OPTION 2: Explicit Iceberg CREATE + INSERT
-- Iceberg Table: match_ids
CREATE TABLE IF NOT EXISTS iceberg.bronze.match_ids (
    match_id VARCHAR,
    puuid VARCHAR,
    platform VARCHAR,
    region VARCHAR,
    queue_id BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET'
);

-- Copy data from Hive to Iceberg
INSERT INTO iceberg.bronze.match_ids
SELECT * FROM hive.lol_bronze.match_ids;


-- ========== MATCHES_PARTICIPANTS ==========

-- OPTION 1: Hive External → Iceberg CTAS (auto schema)
-- Hive External Table: matches_participants
CREATE TABLE IF NOT EXISTS hive.lol_bronze.matches_participants (
    match_id VARCHAR,
    platform VARCHAR,
    queue_id BIGINT,
    game_mode VARCHAR,
    game_version VARCHAR,
    game_duration BIGINT,
    game_creation BIGINT,
    game_start_timestamp BIGINT,
    game_end_timestamp BIGINT,
    puuid VARCHAR,
    summoner_name VARCHAR,
    riot_id_name VARCHAR,
    riot_id_tagline VARCHAR,
    participant_id BIGINT,
    team_id BIGINT,
    side VARCHAR,
    champion_id BIGINT,
    champion_name VARCHAR,
    team_position VARCHAR,
    lane VARCHAR,
    win BOOLEAN,
    kills BIGINT,
    deaths BIGINT,
    assists BIGINT,
    gold_earned BIGINT,
    total_minions_killed BIGINT,
    neutral_minions_killed BIGINT,
    total_ally_jungle_minions_killed BIGINT,
    total_enemy_jungle_minions_killed BIGINT,
    total_damage_dealt_to_champions BIGINT,
    total_damage_taken BIGINT,
    damage_self_mitigated BIGINT,
    total_damage_shielded_on_teammates BIGINT,
    total_heals_on_teammates BIGINT,
    damage_dealt_to_buildings BIGINT,
    damage_dealt_to_objectives BIGINT,
    dragon_kills BIGINT,
    turret_kills BIGINT,
    turrets_lost BIGINT,
    objectives_stolen BIGINT,
    vision_score BIGINT,
    wards_placed BIGINT,
    wards_killed BIGINT,
    control_wards_placed BIGINT,
    first_blood_kill BOOLEAN,
    first_blood_assist BOOLEAN,
    first_tower_kill BOOLEAN,
    first_tower_assist BOOLEAN,
    game_ended_in_early_surrender BOOLEAN,
    game_ended_in_surrender BOOLEAN,
    longest_time_spent_living BIGINT,
    largest_killing_spree BIGINT,
    total_time_cc_dealt BIGINT,
    total_time_spent_dead BIGINT,
    summoner1_id BIGINT,
    summoner2_id BIGINT,
    item0 BIGINT,
    item1 BIGINT,
    item2 BIGINT,
    item3 BIGINT,
    item4 BIGINT,
    item5 BIGINT,
    item6 BIGINT,
    perk_keystone BIGINT,
    perk_primary_row_1 BIGINT,
    perk_primary_row_2 BIGINT,
    perk_primary_row_3 BIGINT,
    perk_secondary_row_1 BIGINT,
    perk_secondary_row_2 BIGINT,
    perk_primary_style BIGINT,
    perk_secondary_style BIGINT,
    perk_shard_defense BIGINT,
    perk_shard_flex BIGINT,
    perk_shard_offense BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET',
    external_location = 's3a://lol-bronze/matches_participants/'
);

-- Iceberg CTAS: matches_participants (auto schema from Hive)
CREATE TABLE IF NOT EXISTS iceberg.bronze.matches_participants AS
SELECT * FROM hive.lol_bronze.matches_participants;


-- OPTION 2: Explicit Iceberg CREATE + INSERT
-- Iceberg Table: matches_participants
CREATE TABLE IF NOT EXISTS iceberg.bronze.matches_participants (
    match_id VARCHAR,
    platform VARCHAR,
    queue_id BIGINT,
    game_mode VARCHAR,
    game_version VARCHAR,
    game_duration BIGINT,
    game_creation BIGINT,
    game_start_timestamp BIGINT,
    game_end_timestamp BIGINT,
    puuid VARCHAR,
    summoner_name VARCHAR,
    riot_id_name VARCHAR,
    riot_id_tagline VARCHAR,
    participant_id BIGINT,
    team_id BIGINT,
    side VARCHAR,
    champion_id BIGINT,
    champion_name VARCHAR,
    team_position VARCHAR,
    lane VARCHAR,
    win BOOLEAN,
    kills BIGINT,
    deaths BIGINT,
    assists BIGINT,
    gold_earned BIGINT,
    total_minions_killed BIGINT,
    neutral_minions_killed BIGINT,
    total_ally_jungle_minions_killed BIGINT,
    total_enemy_jungle_minions_killed BIGINT,
    total_damage_dealt_to_champions BIGINT,
    total_damage_taken BIGINT,
    damage_self_mitigated BIGINT,
    total_damage_shielded_on_teammates BIGINT,
    total_heals_on_teammates BIGINT,
    damage_dealt_to_buildings BIGINT,
    damage_dealt_to_objectives BIGINT,
    dragon_kills BIGINT,
    turret_kills BIGINT,
    turrets_lost BIGINT,
    objectives_stolen BIGINT,
    vision_score BIGINT,
    wards_placed BIGINT,
    wards_killed BIGINT,
    control_wards_placed BIGINT,
    first_blood_kill BOOLEAN,
    first_blood_assist BOOLEAN,
    first_tower_kill BOOLEAN,
    first_tower_assist BOOLEAN,
    game_ended_in_early_surrender BOOLEAN,
    game_ended_in_surrender BOOLEAN,
    longest_time_spent_living BIGINT,
    largest_killing_spree BIGINT,
    total_time_cc_dealt BIGINT,
    total_time_spent_dead BIGINT,
    summoner1_id BIGINT,
    summoner2_id BIGINT,
    item0 BIGINT,
    item1 BIGINT,
    item2 BIGINT,
    item3 BIGINT,
    item4 BIGINT,
    item5 BIGINT,
    item6 BIGINT,
    perk_keystone BIGINT,
    perk_primary_row_1 BIGINT,
    perk_primary_row_2 BIGINT,
    perk_primary_row_3 BIGINT,
    perk_secondary_row_1 BIGINT,
    perk_secondary_row_2 BIGINT,
    perk_primary_style BIGINT,
    perk_secondary_style BIGINT,
    perk_shard_defense BIGINT,
    perk_shard_flex BIGINT,
    perk_shard_offense BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET'
);

-- Copy data from Hive to Iceberg
INSERT INTO iceberg.bronze.matches_participants
SELECT * FROM hive.lol_bronze.matches_participants;


-- ========== MATCHES_TEAMS ==========

-- OPTION 1: Hive External → Iceberg CTAS (auto schema)
-- Hive External Table: matches_teams
CREATE TABLE IF NOT EXISTS hive.lol_bronze.matches_teams (
    match_id VARCHAR,
    team_id BIGINT,
    side VARCHAR,
    win BOOLEAN,
    baron_kills BIGINT,
    dragon_kills BIGINT,
    rift_herald_kills BIGINT,
    tower_kills BIGINT,
    inhibitor_kills BIGINT,
    champion_kills BIGINT,
    first_baron BOOLEAN,
    first_dragon BOOLEAN,
    first_rift_herald BOOLEAN,
    first_tower BOOLEAN,
    first_inhibitor BOOLEAN,
    first_blood BOOLEAN,
    ban_1 BIGINT,
    ban_2 BIGINT,
    ban_3 BIGINT,
    ban_4 BIGINT,
    ban_5 BIGINT,
    game_version VARCHAR,
    queue_id BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET',
    external_location = 's3a://lol-bronze/matches_teams/'
);

-- Iceberg CTAS: matches_teams (auto schema from Hive)
CREATE TABLE IF NOT EXISTS iceberg.bronze.matches_teams AS
SELECT * FROM hive.lol_bronze.matches_teams;


-- OPTION 2: Explicit Iceberg CREATE + INSERT
-- Iceberg Table: matches_teams
CREATE TABLE IF NOT EXISTS iceberg.bronze.matches_teams (
    match_id VARCHAR,
    team_id BIGINT,
    side VARCHAR,
    win BOOLEAN,
    baron_kills BIGINT,
    dragon_kills BIGINT,
    rift_herald_kills BIGINT,
    tower_kills BIGINT,
    inhibitor_kills BIGINT,
    champion_kills BIGINT,
    first_baron BOOLEAN,
    first_dragon BOOLEAN,
    first_rift_herald BOOLEAN,
    first_tower BOOLEAN,
    first_inhibitor BOOLEAN,
    first_blood BOOLEAN,
    ban_1 BIGINT,
    ban_2 BIGINT,
    ban_3 BIGINT,
    ban_4 BIGINT,
    ban_5 BIGINT,
    game_version VARCHAR,
    queue_id BIGINT,
    ingest_ts VARCHAR
) WITH (
    format = 'PARQUET'
);

-- Copy data from Hive to Iceberg
INSERT INTO iceberg.bronze.matches_teams
SELECT * FROM hive.lol_bronze.matches_teams;


-- ========== VERIFICATION ==========

SELECT 'ladder' as table_name, COUNT(*) as row_count FROM iceberg.bronze.ladder;
SELECT 'match_ids' as table_name, COUNT(*) as row_count FROM iceberg.bronze.match_ids;
SELECT 'matches_participants' as table_name, COUNT(*) as row_count FROM iceberg.bronze.matches_participants;
SELECT 'matches_teams' as table_name, COUNT(*) as row_count FROM iceberg.bronze.matches_teams;